name: "t2t_lang"
backend: "python"
max_batch_size: 20
input [
  {
    name: "input_txt"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "language"
    data_type: TYPE_STRING
    dims: [ 1 ]
  },
  {
    name: "score"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }

]

dynamic_batching {
  max_queue_delay_microseconds: 1000000
}

instance_group [{count: 1, kind: KIND_GPU}]